#!/usr/bin/env bash
REQUESTED_ROS_DISTRO=""
ROS_SETUP_PATH=""
OPTIND=1
while getopts ':s:h' opt; do
  case "$opt" in
    s)
      REQUESTED_ROS_DISTRO="$OPTARG"
      echo "Requested system ROS2 $REQUESTED_ROS_DISTRO environment"
      ;;

    h)
      echo "Usage: $(basename $0) [-s system_ros_distro]"
      return
      ;;

    :)
      echo -e "option requires an argument.\nUsage: $(basename $0) [-a] [-b] [-c arg]"
      #exit 1
      return
      ;;

    ?)
      echo -e "Invalid command option.\nUsage: $(basename $0) [-s system_ros_distro]"
      return
      ;;
  esac
done
shift "$(($OPTIND -1))"

SCRIPT_PATH="${BASH_SOURCE[0]}"
BRT_APP_PATH="$(dirname "$SCRIPT_PATH")"
if [[ "$BRT_APP_PATH" != /* ]]; then # check if absolute path
  BRT_APP_PATH="$(pwd)/${BRT_APP_PATH}"
fi

if [ ! -d "$BRT_APP_PATH" ]; then
  echo "ERROR: Path to brt app $BRT_APP_PATH does not exist."
  return
fi

if [ -n "$REQUESTED_ROS_DISTRO"  ]; then
    ROS_SETUP_PATH="/opt/ros/$REQUESTED_ROS_DISTRO/setup.bash"
fi

# activating requested system ROS2 distro if it exists
if [ -n "$ROS_SETUP_PATH" ]; then
  if  [ -f ${ROS_SETUP_PATH} ]; then
    echo "Activating system ROS2 $REQUESTED_ROS_DISTRO environment"
    source ${ROS_SETUP_PATH}
  else
    echo "WARNING: Invalid ROS2 source file ${ROS_SETUP_PATH}, several features may not be available"
  fi
fi

# Populate environment variables present in a colcon produced runtime environment
export AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH:+${AMENT_PREFIX_PATH}:}${BRT_APP_PATH}/brt/ros
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}${BRT_APP_PATH}/brt/ros/lib
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${BRT_APP_PATH}/brt/lib"
export PATH=${PATH:+${PATH}:}${BRT_APP_PATH}/brt/ros/bin:${BRT_APP_PATH}/brt/bin
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH:+${PKG_CONFIG_PATH}:}${BRT_APP_PATH}/brt/ros/lib/pkgconfig
export PYTHONPATH=${PYTHONPATH:+${PYTHONPATH}:}${BRT_APP_PATH}/brt/ros/lib/python3.10/site-packages
#export ROS_LOG_DIR=/var/volatile

# Setting  QoS profiles
#export NDDS_QOS_PROFILES=${BRT_APP_PATH}/brt/usr/share/rti/JUPITER_QOS_PROFILES.xml # This currently fails parsing
export NDDS_QOS_PROFILES=${BRT_APP_PATH}/brt/usr/share/rti/USER_QOS_PROFILES.xml

# variables required by jupiter node
#export DOMAIN_ID=37
#export NDDS_XTYPES_COMPLIANCE_MASK=45
export SYSTEM="bedrock"
export MACHINE_ID=1
#export VPU_POSITION=1

echo "WARNING: Using non-standard ROS2 setup, generated by bazel"
